services:
  devicegalaxy:
    image: restartb/devicegalaxy:latest@sha256:c2e59caea857006c57e101d0c9f6522b76495b325a506473ef448956d7795e7c
    container_name: devicegalaxy
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - './data:/data'
      - './db:/db'
    env_file:
      - .env
