name: New Version Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version name'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
          
      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: '24.16.0'

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump version and create tag
        run: |
          npm version ${{ inputs.version }} -m "Bump version to %s"

      - name: Push commit and tag
        run: |
          git push origin HEAD --follow-tags
